### ISSUE TITLE
Running the GitHub action with ` scorecard: verbose` fails with error `failed to enrich scorecard: expecting []ScorecardCheck`

### ISSUE THREAD

**Issue by rajbos** [Legit-Labs/legitify#260]
### TL;DR

Running the action with `scorecard: verbose` throws an error. Running with `scorecard: yes` works.
``` yaml
   steps:
      - name: Legitify Action
        uses: Legit-Labs/legitify@main
        with:
          github_token: ${{ secrets.GH_PAT }}
          analyze_self_only: true
          scorecard: verbose
``` 
### Expected behavior

A working scan

### Observed behavior

The error seems that to be the issue: `failed to enrich scorecard: expecting []ScorecardCheck`

### Version

main

### On which operating system are you using legitify?

Linux

### Relevant log output

```text
execute legitify analyze: [
  'analyze',
  '--scorecard',
  'verbose',
  '--repo',
  '<org>/<repo>',
  '--ignore-policies-file',
  './ignored-policies',
  '--output-format',
  'json',
  '--output-file',
  'legitify-output.json'
]
execute legitify convert sarif: [
  'convert',
  '--input-file',
  'legitify-output.json',
  '--output-format',
  'sarif',
  '--output-file',
  'legitify-output.sarif'
]
Error: The process '/home/runner/work/_actions/Legit-Labs/legitify/main/legitify' failed with exit code 1 | stderr: Error: failed to parse flattened scheme: failed to parse aux for violation: failed to enrich scorecard: expecting []ScorecardCheck

Error: Error: The process '/home/runner/work/_actions/Legit-Labs/legitify/main/legitify' failed with exit code 1
```
